### ISSUE TITLE
4个文件找不到

### ISSUE THREAD

**Issue by xrinkun** [zhfei/BottomComponentLib#1]
"NSDateFormatter+ShortCut.h"
"UIView+Draw.h"
"UIColor+Transform.h"
"UIImage+Custom.h"
看了下分类里确实没有这四个文件啊，我是通过pod安装的

**Comment by zhfei** [comment]
hi,你上面写的分类是BottomComponentLib库开始时的命名形式。为了统一命名规范，后面都采用
“类名+ BCLib”的形式。 所以你上面列的文件名找不到了。
